# Generated by Django 4.0.2 on 2022-03-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy_invoice', '0001_initial_squashed_0011_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.PositiveSmallIntegerField(choices=[(19, '19%'), (7, '7%')], verbose_name='VAT rate'),
        ),
    ]
