# Generated by Django 4.0 on 2021-12-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billy_invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "Invoice", "verbose_name_plural": "Invoices"},
        ),
        migrations.AlterModelOptions(
            name="invoiceitem",
            options={
                "verbose_name": "Invoice item",
                "verbose_name_plural": "Invoice items",
            },
        ),
    ]
