# Generated by Django 4.0 on 2021-12-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billy_invoice", "0004_remove_invoice_create_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="price_per_unit",
            field=models.PositiveBigIntegerField(
                verbose_name="Price per unit (in Cents)"
            ),
        ),
    ]
