# Generated by Django 4.0 on 2021-12-11 23:13

from django.db import migrations, models


def populate_invoice_date(apps, schema_editor):
    """
    Populate the field invoice date.
    """
    db_alias = schema_editor.connection.alias
    Invoice = apps.get_model("billy_invoice", "Invoice")

    Invoice.objects.using(db_alias).filter(invoice_date=None).update(
        invoice_date=models.F("created")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("billy_invoice", "0007_alter_invoiceitem_netto_price_per_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Invoice date"
            ),
        ),
        migrations.RunPython(
            code=populate_invoice_date, reverse_code=migrations.RunPython.noop
        ),
    ]
