# Generated by Django 4.0 on 2021-12-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billy_invoice", "0008_invoice_invoice_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(auto_now_add=True, verbose_name="Invoice date"),
        ),
    ]
