# Generated by Django 4.0 on 2021-12-11 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("billy_invoice", "0009_alter_invoice_invoice_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Invoice date"
            ),
        ),
    ]
