# Generated by Django 4.0 on 2021-12-11 23:23

import billy_invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy_invoice', '0010_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=billy_invoice.models.today, verbose_name='Invoice date'),
        ),
    ]
