# Generated by Django 4.0 on 2021-12-16 20:56

from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    replaces = [
        ("billy_customer", "0001_initial"),
        ("billy_customer", "0002_alter_address_address_2_alter_address_address_3"),
        ("billy_customer", "0003_alter_address_options"),
        ("billy_customer", "0004_alter_address_options_alter_customer_options"),
        (
            "billy_customer",
            "0005_address_create_timestamp_address_update_timestamp_and_more",
        ),
        ("billy_customer", "0006_remove_address_create_timestamp_and_more"),
        ("billy_customer", "0007_address_hidden_customer_hidden"),
        ("billy_customer", "0008_remove_customer_addresses"),
        ("billy_customer", "0009_customeraddress"),
        ("billy_customer", "0010_customer_addresses"),
        ("billy_customer", "0011_customer_first_name_customer_last_name"),
        (
            "billy_customer",
            "0012_remove_customer_name_alter_customer_first_name_and_more",
        ),
        ("billy_customer", "0013_address_uq_everything"),
        ("billy_customer", "0014_customeraddress_uq_customer_address"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_1",
                    models.CharField(max_length=100, verbose_name="Address 1"),
                ),
                (
                    "address_2",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Address 2"
                    ),
                ),
                (
                    "address_3",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Address 3"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "postal_code",
                    models.CharField(max_length=5, verbose_name="Postal code"),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("hidden", models.BooleanField(default=False, verbose_name="Hidden")),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "verbose_name": "Address",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("hidden", models.BooleanField(default=False, verbose_name="Hidden")),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("hidden", models.BooleanField(default=False, verbose_name="Hidden")),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="billy_customer.address",
                        verbose_name="Address",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="billy_customer.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="addresses",
            field=models.ManyToManyField(
                through="billy_customer.CustomerAddress",
                to="billy_customer.Address",
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=100, null=True, verbose_name="Last name"),
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last name"),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                fields=("address_1", "address_2", "address_3", "city", "postal_code"),
                name="uq_everything",
            ),
        ),
        migrations.AddConstraint(
            model_name="customeraddress",
            constraint=models.UniqueConstraint(
                fields=("customer", "address"), name="uq_customer_address"
            ),
        ),
    ]
