# Generated by Django 4.0 on 2021-12-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address 3'),
        ),
    ]
