# Generated by Django 4.0.2 on 2022-02-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy_customer', '0002_alter_customeraddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.PositiveIntegerField(null=True, verbose_name='Customer number'),
        ),
    ]
