# Generated by Django 4.0 on 2021-12-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billy_customer", "0003_alter_address_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        ),
    ]
