# Generated by Django 4.0 on 2021-12-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billy_customer", "0004_alter_address_options_alter_customer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="create_timestamp",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Create timestamp"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="update_timestamp",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Update timestamp"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="create_timestamp",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Create timestamp"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="update_timestamp",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Update timestamp"
            ),
        ),
    ]
