# Generated by Django 4.0 on 2021-12-11 22:11

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billy_customer', '0005_address_create_timestamp_address_update_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='address',
            name='update_timestamp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='update_timestamp',
        ),
        migrations.AddField(
            model_name='address',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='address',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
