# Generated by Django 4.0 on 2021-12-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billy_customer", "0006_remove_address_create_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
        migrations.AddField(
            model_name="customer",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
    ]
