# Generated by Django 4.0 on 2021-12-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billy_customer", "0007_address_hidden_customer_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="addresses",
        ),
    ]
