# Generated by Django 4.0 on 2021-12-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billy_customer", "0009_customeraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="addresses",
            field=models.ManyToManyField(
                through="billy_customer.CustomerAddress",
                to="billy_customer.Address",
                verbose_name="Address",
            ),
        ),
    ]
