# Generated by Django 4.0 on 2021-12-14 10:25

from django.db import migrations, models


def populate_first_and_last_name(apps, schema_editor):
    """
    Populate first and last name
    """
    db_alias = schema_editor.connection.alias
    Customer = apps.get_model("billy_customer", "Customer")

    for customer in Customer.objects.using(db_alias).all():
        names, last_name = customer.name.rsplit(" ", 1)

        customer.first_name = names
        customer.last_name = last_name
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ("billy_customer", "0010_customer_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=100, null=True, verbose_name="Last name"),
        ),
        migrations.RunPython(
            code=populate_first_and_last_name, reverse_code=migrations.RunPython.noop
        ),
    ]
