# Generated by Django 4.0 on 2021-12-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billy_customer", "0011_customer_first_name_customer_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last name"),
        ),
    ]
