# Generated by Django 4.0 on 2021-12-09 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('price', models.PositiveBigIntegerField(verbose_name='Price')),
                ('details', models.JSONField(verbose_name='Details')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='billy_warehouse.vendor', verbose_name='Vendor')),
            ],
        ),
    ]
