# Generated by Django 4.0 on 2021-12-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billy_warehouse', '0001_initial_squashed_0011_product_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'category__name', 'vendor__name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
    ]
