# Generated by Django 4.0 on 2021-12-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy_warehouse', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='attributes_form_defintion',
            field=models.JSONField(blank=True, null=True, validators=[], verbose_name='Attributes form definition'),
        ),
    ]
