# Generated by Django 4.0 on 2021-12-31 00:28

import billy_warehouse.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billy_warehouse', '0003_category_attributes_form_defintion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='attributes_form_defintion',
            field=billy_warehouse.models.JSONFormDefinitionField(blank=True, null=True, verbose_name='Attributes form definition'),
        ),
    ]
