# Generated by Django 4.0 on 2021-12-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billy_warehouse", "0003_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="billy_warehouse.category",
                verbose_name="Category",
            ),
        ),
    ]
