# Generated by Django 4.0 on 2022-01-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy_warehouse', '0007_alter_product_netto_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='netto_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Netto price (in Cents)'),
        ),
    ]
