# Generated by Django 4.0 on 2021-12-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billy_warehouse', '0008_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='netto_price',
        ),
    ]
