# Generated by Django 4.0.2 on 2022-02-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy_warehouse', '0009_alter_product_netto_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='details_template',
            field=models.TextField(blank=True, help_text='Used in products overview', null=True, verbose_name='Details template'),
        ),
    ]
