# Generated by Django 4.0 on 2021-12-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billy_warehouse", "0010_alter_product_netto_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
    ]
