# Generated by Django 4.0.2 on 2022-02-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy_warehouse', '0010_category_details_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='details_form',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Attributes form definition'),
        ),
        migrations.AlterField(
            model_name='category',
            name='details_template',
            field=models.CharField(blank=True, help_text='Used in products overview', max_length=255, null=True, verbose_name='Details template'),
        ),
    ]
