# Generated by Django 4.0.2 on 2022-02-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy_warehouse', '0011_alter_category_details_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='details_form',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Attributes form class'),
        ),
        migrations.AlterField(
            model_name='category',
            name='details_template',
            field=models.CharField(blank=True, help_text='Used in products overview', max_length=255, null=True, verbose_name='Details template path'),
        ),
    ]
