# Generated by Django 4.0.2 on 2022-03-28 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billy_warehouse', '0012_alter_category_details_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('rowid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='billy_warehouse.product')),
                ('search_document', models.TextField(verbose_name='Search document')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RunSQL(sql="""
            CREATE VIRTUAL TABLE billy_warehouse_productsearch USING FTS5(search_document, content=billy_warehouse_product, content_rowid=id)
        """, reverse_sql="""
            DROP TABLE billy_warehouse_productsearch
        """),
        migrations.AddField(
            model_name='category',
            name='search_document_generator',
            field=models.CharField(blank=True, help_text='This function should return a list of strings (Callable[[Product], Sequence[str]]', max_length=255, null=True, verbose_name='Function to generate the search document'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_document',
            field=models.TextField(default='', verbose_name='Search document'),
        ),
    ]
