# Generated by Django 4.0.4 on 2022-04-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy_warehouse', '0013_productsearch_category_search_document_generator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='search_document_generator',
            field=models.CharField(blank=True, help_text='This function should return a string containing words for the search index (Callable[[Product], str])', max_length=255, null=True, verbose_name='Function to generate the search document'),
        ),
    ]
